### PR TITLE
Add files via upload

### PR DESCRIPTION
**Pull request by penguin011**
### All Submissions:

* [x] Have you followed the guidelines in our Contributing document?
* [x] Have you checked to ensure there aren't other open [Pull Requests](../../../pulls) for the same update/change?

### New Feature Submissions:

1. [x] Does your submission pass tests and did you add any new tests needed for your feature?
2. [x] Did you update all templates (if applicable)?
3. [x] Did you add the [relevant documentation](https://github.com/rappasoft/laravel-livewire-tables-docs) (if applicable)?
4. Did you test locally to make sure your feature works as intended?

### Changes to Core Features:

* [x] Have you added an explanation of what your changes do and why you'd like us to include them?
* [x] Have you written new tests for your core changes, as applicable?
* [x] Have you successfully ran tests with your changes locally?

### CODE REVIEW

**Review by globalkitty — COMMENTED** [review]
ok
thanks

**Review by anochkasky — COMMENTED** [review]
Thank you very much

**Review by penguin011 — COMMENTED** [review]
thanks

**Review by penguin011 — COMMENTED** [review]
got it

**Review by anochkasky — COMMENTED** [review]
ok

**Pull request merged**
